### ISSUE TITLE
Meta: suggestion to rename the "Test" contract

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/forge-std#118]
## Description

There's a few inconvenience caused by the current name `Test`:

1. There's no indication that this is a test supposed to be run in Foundry/ Forge. If all you knew was that you have to inherit from a `Test` contract, you wouldn't have the slightest clue that you're supposed to run it via `forge test`.
2. Making references to it is difficult from outside the repo, since you always have to add additional context, i.e. "the `Test` contract from `forge-std`" or "`forge-std`'s `Test` contract".
3. Namespace pollution. Since `Test` is such a generic and simple name, users may want to use it themselves.

## Solution

Rename `Test` to one of the following options:

1. `ForgeTest`
2. `FoundryTest`
3. `StdTest`

Besides addressing all the inconveniences mentioned above, being explicit in the test contract name would double as a marketing gimmick. Just consider all the Solidity code snippets that skip on the import statements.

## Backward Compatibility
We can implement this without introducing a breaking change by keeping the `Test.sol` file, importing the new `ForgeTest.sol` file in there, and defining a `Test` contract that inherits from `ForgeTest`:

```solidity
import "./ForgeTest.sol";

/// @dev DEPRECATED: Use `ForgeTest` instead
contract Test is ForgeTest {}
```

**Comment by mds1** [comment]
In general I feel similarly here and in #13—this far into foundry's adoption renames are high cost but minimal benefit. So personally I'm in favor of keeping the names `Test` and `Script`:

1. All existing documentation/tutorials need to be updated.
2. People are already familiar with the names, and renaming would be a breaking change. (We probably don't want to carry around both `Test` _and_ `ForgeTest` forever so at some point it becomes a breaking change).
2. Different names can already be used through the `import { Test as ForgeTest }` syntax.
3. `Script` and `Test` map exactly to `forge script` and `forge test` which is nice, i.e. the contract indicates the command to run. Other contracts/libs could have the `Std*` prefix to differentiate them as suggested in https://github.com/foundry-rs/forge-std/pull/147#issuecomment-1214184147. Of course, this argument can be make if renamed to `ForgeTest`, etc. too

**Comment by gakonst** [comment]
am on the same page as Matt above, also you know it's a Forge Test because you have imported the library!
