### ISSUE TITLE
Meta: Unbundling Test from Script

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/forge-std#124]
## Description

Commit [f18682b2][1] made by @devanonon added two new utility functions in the `Script` contract:

1. `computeCreateAddress`
2. `addressFromLast20Bytes`

Which are of course very useful in the context of deploying contracts (the main feature of Solidity Scripting).

But now this makes it confusing that the `Test` contract [inherits](https://github.com/foundry-rs/forge-std/blob/c19dfd2f2a88a461216b0dd1f4961e1a85dcad46/src/Test.sol#L8) from `Script`. Why should it? They seem to be two separate concerns. If a user just so happens to define a function called `run` in their tests, that would be treated as a script entrypoint by Forge.

If the goal was to add the `vm` property to `Test`, we could simply redeclare the `VM_ADDRESS` and the `vm` variables in `Test`. Redundancy is not intrinsically bad. 

Actually, even before commit [f18682b2][1], I was a bit confused by the fact that the `Test` contract inherits from`Script`. Even in the Foundry Book, there's an implicit distinction made between [Writing Tests](https://book.getfoundry.sh/forge/writing-tests) and [Solidity Scripting](https://book.getfoundry.sh/tutorials/solidity-scripting). So even if this proposal isn't accepted, at the very least we should add a warning in the Foundry Book that contracts inheriting from `Test` also inherit from `Script`.

## Solution

1. Remove the inheritance from `Script` in `Test`.
2. Redeclare `VM_ADDRESS` and `vm` in `Test`.
3. Rewrite the methods in `Script` to have public visibility.
4. Rewrite the tests in `Script.t.sol` to instantiate an internal test contract `script`.

## Caveats

1. If this proposal passes, a child contract couldn't inherit from both at the same time, but if I understand the goals of `Test` and `Script` correctly, users are not expected to do this anyway.
2. As I understand it, Foundry excludes all contracts with the `IS_SCRIPT` flag set to `true` from the gas reports. But does it also exclude `IS_TEST` contracts? If yes, then this isn't a problem. But if not, why? If it does that for scripts it should also it for pure tests contracts. Happy to open an issue in Foundry to track this.

[1]: (https://github.com/foundry-rs/forge-std/commit/f18682b2874fc57d7c80a511fed0b35ec4201ffa)

**Comment by paulrberg** [comment]
Closing as completed since https://github.com/foundry-rs/forge-std/pull/126 has been merged on the v0.3 branch.

**Comment by devanonon** [comment]
@paulrberg amazing, I've been away the last few days but agree with all your changes. Appreciate it! <3
