### ISSUE TITLE
Meta: Upstreaming the assertions to PRBTest

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/forge-std#128]
This discussion is contingent on [bumping the pragma to `>=0.8.0 <0.9.0`](https://github.com/foundry-rs/forge-std/issues/125).

Building up on the arguments I have made in [Why Choose PRBTest Over DSTest?](https://github.com/paulrberg/prb-test/tree/ce5d128391feb6f64dff05d8d4431c799646b2c5#why-choose-prbtest-over-dstest):

1. Switching to PRBTest would free Forge Std of the path dependence problem that plagues DSTest (that is, all DappHub projects depend upon DSTest, so updating it is painful to orchestrate). PRBTest is a brand new project, and I have designed it from the get go to never suffer from path dependence.
2. Letting PRBTest handle all testing assertions would take a burden off the shoulders of Forge Std. Forge Std could instead focus on its juiciest features, such as `StdStorage`, and could continue "moving fast and breaking things" knowing that unless PRBTest is explicitly version bumped, the assertion syntax will remain the same.
3. Forge Std wouldn't have to maintain the `Vm` interface anymore.
4. Forge Std wouldn't have to maintain the tests in `StdAssertions.t.sol` anymore.
5. PRBTest has a more permissive license than DSTest. MIT versus GPL v3.

Finally, on a personal level, Foundry has become my primary development framework. It's what [I recommend](https://twitter.com/PaulRBerg/status/1546810106934923265) to anyone looking to jump into Ethereum development. I've also recently become a frequent contributor to Forge Std and the Foundry Book. Upstreaming the assertions to PRBTest would make us both more agile.

**Comment by ZeroEkkusu** [comment]
Closing, as discussed in #139.
