### ISSUE TITLE
CapWords naming sytle

### ISSUE THREAD

**Issue by ZeroEkkusu** [foundry-rs/forge-std#13]
Is there a reason why the names of the contracts and libraries don't begin with a capital letter?

E.g. `stdCheats` --> `StdCheats`

**Comment by ZeroEkkusu** [comment]
Whoa, this issue is old; I barely knew how to use Foundry back then.

But, yeah, I'm still for this.

**Comment by gakonst** [comment]
Closing as #wontfix per conversation [here](https://github.com/foundry-rs/forge-std/pull/69#issuecomment-1129408485). LMK if anyone disagrees / feels strongly about re-opening.

**Comment by mds1** [comment]
Reopening this as something we may implement as part of breaking changes as discussed in https://github.com/foundry-rs/forge-std/pull/126#discussion_r924699853
