### ISSUE TITLE
Adding payable fallback to Test.sol

### ISSUE THREAD

**Issue by TotalPizza** [foundry-rs/forge-std#136]
I understand the principle that users shouldn't have to assume that the Test.sol contract has a payable fallback function by default.

However, in my experience the test contracts that inherit from `Test.sol` are usually used to simulate user (EOA) interactions rather then expecting for a contract that inherits from `Test.sol` to be deployable on-chain. Therefore users won't expect that receiving any ETH (e.g. when unwrapping WETH) will cause an error.

In my experience it also takes a while to find the cause of a transaction that was reverted due to a missing fallback function as the error message isn't very specific (especially newcomers will struggle with this).

Although not vital by any means, placing `receive() external payable {}` into the `Test.sol` contract will probably will reduce developer headaches and the number of future error reports by quite a bit.

**Comment by brockelmore** [comment]
This may be an extremely hot take, but either the developer already knows why it failed and knows it needs a `receive` or they don't know either of those and need to learn it.

Either way, I am going to pass on the recommendation because I find it counter-intuitive for a contract to default accept ETH

Others may have opinions on this that they can air and maybe I can be convinced

**Comment by TotalPizza** [comment]
I find that to be a very based take.

It's probably sufficient if I create a StackOverflow entry (or something of that sorts) which beginners that run into that issue can find if they perform a web search.

**Comment by mds1** [comment]
Worth noting too that forge will be improved to give better error messages in cases like this, so it will become easier to detect:
- https://github.com/foundry-rs/foundry/issues/1387
- https://github.com/foundry-rs/foundry/pull/2130
