### ISSUE TITLE
forge script not recognizing env vars

### ISSUE THREAD

**Issue by marcusmolchany** [foundry-rs/forge-std#141]
i have a `.env.local` file with environment variables that i am loading into my shell before running my forge script. the forge script isn't picking up the environment variables when i try to load them using the `env` cheatcodes:

#### `env.local`
```
BOOL_ENV_VAR=true
BOOL_ENV_VAR_2=false
STRING_ENV_VAR="I am a string"
```

#### `script/Contract.s.sol`
```sh
➜  env-vars-in-script git:(main) source .env.local && echo $BOOL_ENV_VAR && echo $BOOL_ENV_VAR_2 && echo $STRING_ENV_VAR && forge script script/Contract.s.sol -vvvvv
true
false
I am a string
[⠆] Compiling...
No files changed, compilation skipped
Traces:
  [98] ContractScript::setUp()
    └─ ← ()

  [2944] ContractScript::run()
    ├─ [0] VM::envBool("BOOL_ENV_VAR")
    │   └─ ← "environment variable not found"
    └─ ← "environment variable not found"


Script failed.
Gas used: 2944

== Return ==
Error:
Script failed.
```

## repo with example: https://github.com/marcusmolchany/foundry-env-vars-in-script

**Comment by sambacha** [comment]
When you source the file, the const assignments will be set but the variables are not exported unless the allexport option has been set. you enable allexport by doing set +a

so just do:

`set +a  . env.local; set -a;`

https://man7.org/linux/man-pages/man1/set.1p.html

**Comment by marcusmolchany** [comment]
@sambacha thanks for the reply! i used `set +a` and i'm still getting the same results:

```sh
➜  env-vars-in-script git:(main) set +a . env.local; echo $BOOL_ENV_VAR && echo $BOOL_ENV_VAR_2 && echo $STRING_ENV_VAR && forge script script/Contract.s.sol -vvvvv        
true
false
I am a string
[⠆] Compiling...
No files changed, compilation skipped
Traces:
  [98] ContractScript::setUp() 
    └─ ← ()

  [2944] ContractScript::run() 
    ├─ [0] VM::envBool("BOOL_ENV_VAR") 
    │   └─ ← "environment variable not found"
    └─ ← "environment variable not found"


Script failed.
Gas used: 2944

== Return ==
Error: 
Script failed.
```

**Comment by marcusmolchany** [comment]
a solution from the foundry support telegram that worked for me:

### 1. add `export` in front of the env vars in `.env.local`:
```sh
export BOOL_ENV_VAR=true
export BOOL_ENV_VAR_2=false
export STRING_ENV_VAR="I am a string"
```

### 2. use same cli command as before:
```sh
$ source .env.local && echo $BOOL_ENV_VAR && echo $BOOL_ENV_VAR_2 && echo $STRING_ENV_VAR && forge script script/Contract.s.sol -vvvvv
```

### ⚠️ this will set these env vars globally. use `unset VAR_NAME` to unset them in your shell

**Comment by sambacha** [comment]
You missed the . Before the local.env, that is how you source the dotenv file, or you can type out source too.

**Comment by marcusmolchany** [comment]
@sambacha like this? i'm still getting the same error:

```sh
➜  env-vars-in-script git:(main) ✗ set +a . .env.local; echo $BOOL_ENV_VAR && echo $BOOL_ENV_VAR_2 && echo $STRING_ENV_VAR && forge script script/Contract.s.sol -vvvvv



[⠢] Compiling...
No files changed, compilation skipped
Traces:
  [98] ContractScript::setUp() 
    └─ ← ()

  [2944] ContractScript::run() 
    ├─ [0] VM::envBool("BOOL_ENV_VAR") 
    │   └─ ← "environment variable not found"
    └─ ← "environment variable not found"


Script failed.
Gas used: 2944

== Return ==
Error: 
Script failed.
```

**Comment by mds1** [comment]
@marcusmolchany Is this still an issue? In https://github.com/foundry-rs/forge-std/issues/141#issuecomment-1202975626 it sounds like you found a working solution (that's the approach I use also)

**Comment by onbjerg** [comment]
We can close this, adding `export` before the variables is a requirement of `source` which we are not in control of - if the file was named `.env` it would be autoloaded and work with and without `export`
