### ISSUE TITLE
"Member "sig" is not available in struct StdStorage storage pointer outside of storage" on compiler 0.6.9

### ISSUE THREAD

**Issue by traceurl** [foundry-rs/forge-std#144]
Hi guys, I encountered this error when testing my contract using forge-std. My contract was written in solidity 0.6.9
```
Compiler run failed
lib/forge-std/src/Test.sol:92:9: TypeError: Member "sig" is not available in 
        stdstore
        ^ (Relevant source part starts here and spans across multiple lines).
```
And here is where the error pops out, in forge-std/src/Test.sol, line 117 and line 92.
![Screen Shot](https://user-images.githubusercontent.com/25892474/182382058-b9d48500-f4e1-48fd-847e-07f790841c1e.png).

**Comment by mds1** [comment]
Are you seeing an error when compiling, or just in the VSCode tooltip? I suspect it may just be an issue with VSCode/the extension

**Comment by ZeroEkkusu** [comment]
I think this may be a bug in Solidity `0.6.9`.

[This](https://web.archive.org/web/20210303235351/https://blog.soliditylang.org/2020/06/11/solidity-0610-release-announcement/) is the release announcement for `0.6.10`. They recommend upgrading to `0.6.10` anyway, as `0.6.9` is only one week older.

**Comment by traceurl** [comment]
> Are you seeing an error when compiling, or just in the VSCode tooltip? I suspect it may just be an issue with VSCode/the extension

In compiling

**Comment by brockelmore** [comment]
@traceurl so confirmed 0.6.9 bug? can we close this?

**Comment by traceurl** [comment]
@brockelmore Yes, this is a 0.6.9 bug. After updating to 0.6.10, this problem fixed.
