### ISSUE TITLE
EvmError: Revert. Reverting even though functions working succesfully?

### ISSUE THREAD

**Issue by Maurechi** [foundry-rs/forge-std#149]
![Screenshot 2022-08-09 at 16 50 09](https://user-images.githubusercontent.com/71376233/183862760-896b778d-e458-4b9e-b223-0cc72b51aa42.png)

I've got a simple function that repays a borrow from a compound fork. The interaction with the fork works fine, emits events. I changed the bytecode of it to log all interactions and they are all working good. But for some reason it is still reverting. 

My function only does this. This is a borrowRepay in Matic.

```
   function repayBorrow() external payable onlyVault {
        oRef.repayBorrow{value: msg.value}();
    }
```

 I've tried doing the same with a borrowRepay of an ERC20 and there are no reverts.  I've tried warping block.timestamp, same with block.number. No changes. This is all happening while testing
![Screenshot 2022-08-09 at 17 48 25](https://user-images.githubusercontent.com/71376233/183866517-08bf1583-b9b0-4e78-b226-b35928c8b190.png)

This last picture is the same function with ERC20.  They both have the same traces, both emit a succesfull repayBorrow event. But one reverts afterwards and the other one doesn't. 
.

**Comment by Maurechi** [comment]
Or, since I'm actually getting something similar while using Scripts. Would it be possible to refine these EvmError messages to a be a bit more descriptive?

**Comment by 0xSierraSec** [comment]
Did you ever get a solution to this I'm having same problem.

**Comment by Maurechi** [comment]
@0xSierraSec i'm not exactly sure what was it at the time. But I think more than likely it had to do with the function return. If you're calling a function that you think should return something and it doesn't, or the other way around. That can break things.
