### ISSUE TITLE
support more uint types in assert

### ISSUE THREAD

**Issue by odyslam** [foundry-rs/forge-std#165]
I would like to PR some `assert` functions for `uint32`, which I use all the time, but I have to cast to uint256 to be asserted.

- We can have `assert` overloading
- We can have new functions that do the casting, as in [DSTestPlus](https://github.com/transmissions11/solmate/blob/main/src/test/utils/DSTestPlus.sol)

Opening this issue to align first, before diving into the PR

**Comment by mds1** [comment]
Supportive of this. I think the 4 overloads in [solmate's DSTestPlus](https://github.com/transmissions11/solmate/blob/9cf1428245074e39090dceacb0c28b1f684f584c/src/test/utils/DSTestPlus.sol#L75-L89) are all common enough that we can pretty much just add this:

```solidity
function assertEq(uint128 a, uint128 b) internal virtual {
    assertEq(uint256(a), uint256(b));
}

function assertEq(uint64 a, uint64 b) internal virtual {
    assertEq(uint256(a), uint256(b));
}

function assertEq(uint96 a, uint96 b) internal virtual {
    assertEq(uint256(a), uint256(b));
}

function assertEq(uint32 a, uint32 b) internal virtual {
    assertEq(uint256(a), uint256(b));
}
```
