### ISSUE TITLE
Path needs an updated to "../lib/ds-test/src/test.sol"

### ISSUE THREAD

**Issue by mmsaki** [foundry-rs/forge-std#186]
https://github.com/foundry-rs/forge-std/blob/efbd3b0fd57edefce908219eac4a051bf928e531/src/Test.sol#L5

**Comment by ZeroEkkusu** [comment]
Are you facing some issue? `ds-test/` is a remapping for `lib/ds-test/src/`.

So,

```solidity
import "ds-test/test.sol"; 
```

Resolves to:

```solidity
import "lib/ds-test/src/test.sol"; 
```

**Comment by mmsaki** [comment]
ok got it. Thank you!
