### ISSUE TITLE
feat: add common interfaces to forge-std

### ISSUE THREAD

**Issue by mds1** [foundry-rs/forge-std#192]
Add ERC-20, 165, 721, 1155, and 4626 interfaces so devs don't need to install OZ or other libs to use them. This matches the set of default interfaces included by vyper: https://github.com/vyperlang/vyper/tree/master/vyper/builtin_interfaces

Note that name and symbol are technically optional in ERC-20, so vyper and OZ both split those into separate files. But I don't think I've seen a token that doesn't have name/symbol, so perhaps we just include that by default in a single IERC20 interface?

h/t @brockelmore

**Comment by pedrommaiaa** [comment]
This issue can be closed now @ZeroEkkusu @mds1
