### ISSUE TITLE
`ds-test` not found when installing `forge-std` as an npm package.

### ISSUE THREAD

**Issue by maurelian** [foundry-rs/forge-std#208]
The `package.json` file added in #176 (despite coming from our team), doesn't seem to work.

You can see that [this PR](https://github.com/ethereum-optimism/optimism/pull/3862/files#diff-e0bec1574ed7d33a08bdec60867b380824283a44aa2bbef4c576dd5a38c49cf7), which updates the commit from one prior to adding it (f18682b2874fc57d7c80a511fed0b35ec4201ffa) to the 1.0.0 commit (17656a2fa5453f495d8c1302a0cedded912457eb), breaks the build. 
The [error](https://github.com/ethereum-optimism/optimism/pull/3862#issuecomment-1301555851) is due to being unable to find the `ds-test` dependency, which doesn't seem to be included with the current package.

A `package.json` was also recently added to `ds-test`, so it could be added as a dependency to the `forge-std` package, however I'm not sure how to handle the different remappings that would be required if `ds-test` is installed to `node_modules` rather than as a submodule.

**Comment by mds1** [comment]
Hmm, interesting. So once change is that ds-test is now imported using relative paths, which I'd think should help any remappings issues when installed in `node_modules` As for ds-test not being included, I'm _far_ from an npm/yarn expert but perhaps there is someway to specify to include submodules during the install, analogous to `git clone --recurse-submodules`? How did ds-test get installed before? Is ds-test present and just not found, or not at all installed?

**Comment by maurelian** [comment]
> How did ds-test get installed before? Is ds-test present and just not found, or not at all installed?

It's also (and was previously) installed using `yarn` as well ([see both here](https://github.com/ethereum-optimism/optimism/blob/1d7c53e444e29aee8db6018c7ee32539d4524041/packages/contracts-bedrock/package.json#L68-L70)). 

After some debugging, I'm able to fix this by manually editing the import paths in Test.sol and StdAssertions.sol like so:

```diff
- import "../lib/ds-test/src/test.sol";
+ import "ds-test/test.sol";
```

However without changing those, I'm unable to make it work by modifying the remappings in the [config file](https://github.com/ethereum-optimism/optimism/pull/3862/files#diff-c434c902a2796590efacfe5ef03fa1cc6c4842368a42f270a607a5def351e1bfR13-R14). It seems as though forge is ignoring the remapping, and just looking at the location relative to the source files. Do remapping not work on relative paths?

**Comment by maurelian** [comment]
I looked in to using a `postinstall` script

https://github.com/maurelian/forge-std/blob/fix/npm/package.json#L17

But that is apparently [very buggy](https://github.com/yarnpkg/yarn/issues/5476) in `yarn`.

**Comment by mattsse** [comment]
I think what's happening here

https://github.com/ethereum-optimism/optimism/blob/1d7c53e444e29aee8db6018c7ee32539d4524041/packages/contracts-bedrock/package.json#L68-L70

is that both are installed at the same level, right?

but forge-std expects `./forge-std/lib/ds-test` but `ds-test` will be installed under `./ds-test`.

so relative paths into submodules are an issue. 

I consider using this via yarn a valid use case, perhaps we should revert the relative import @mds1 ?
I think having issues with duplicate ds-test versions is less likely, and I would consider this a code smell.

**Comment by mds1** [comment]
@mattsse I agree with your assessment, opened https://github.com/foundry-rs/forge-std/pull/210 to resolve. @maurelian can you test out installing forge-std at that commit?

**Comment by maurelian** [comment]
Yep, that commit (5bafa16b4a6aa67c503d96294be846a22a6f6efb) works thanks! 

Should we use that commit, or the current tip of master (on which CI seems to be failing)?

**Comment by mattsse** [comment]
is unrelated, afaik.

forge-std is back on remappings. so I think we can close this?

**Comment by PaulRBerg** [comment]
So, is it an acknowledged limitation of Forge Std that it cannot be installed as an npm package?

I've installed Forge Std and DSTest like this:

```json
"dependencies": {
  "ds-test": "github:dapphub/ds-test",
  "forge-std": "github:foundry-rs/forge-std"
},
```

But couldn't manage to use Forge Std:

https://app.warp.dev/block/ngdqKqj4NZXwAPd0oZ20dj
