### ISSUE TITLE
Make bytesToUint internal or public

### ISSUE THREAD

**Issue by NoahMarconi** [foundry-rs/forge-std#221]
Currently unavailable for json parsing as it's marked private: https://github.com/foundry-rs/forge-std/blob/f50a63aa9ed5e1aed19df1a39a81e005b8ed119d/src/StdCheats.sol#L469

**Comment by NoahMarconi** [comment]
if no objections, I can add a tiny PR

**Comment by ZeroEkkusu** [comment]
If this is a desirable feature, you can add in `StdUtils`.

**Comment by NoahMarconi** [comment]
@ZeroEkkusu I put it in a tiny `library` and access it from `StdUtils` and `StdCheatsSafe` to not run into inheritance conflicts. Open to suggestion if another strategy preferred:

https://github.com/foundry-rs/forge-std/pull/222
