### ISSUE TITLE
setUp() error?

### ISSUE THREAD

**Issue by emhum** [foundry-rs/forge-std#230]
[FAIL. Reason: Invalid data] setUp() (gas: 0)
Test result: FAILED. 0 passed; 1 failed; finished in 420.50µs

**Comment by emhum** [comment]
forge init project and use forge test but get error.

**Comment by 5hanth** [comment]
sirs.

**Comment by shioju** [comment]
You can use an older version of this library to avoid the issue. Commit `51be71e` is the latest commit that works for me. It started breaking in commit `f50a63a`.

**Comment by shioju** [comment]
updating foundry with `foundryup` fixed it for me.

**Comment by mds1** [comment]
Closing this, but feel free to reopen if you're still seeing issues
