### ISSUE TITLE
Remove `Components.sol`

### ISSUE THREAD

**Issue by ZeroEkkusu** [foundry-rs/forge-std#239]
Breaking change.

This will have minimal impact on composability.

## Problem

`Components.sol`

```
import A
import B
import C
```

`Test.sol`

```
import A, B from Components
```

The selective import causes `C` to compile as well. This will increase the compilation time as components pile up.

## Solution

Remove `Components.sol`. Require importing directly from files (most users do this anyway).

Let's include this in `1.2.0`.

**Comment by mds1** [comment]
Sorry do you mind clarifying the problem here? I though if you do `import {A, B} from "./Components.sol"` then solc would know `C` is not used and not compile it

Regardless, I'm ok dropping the `Components.sol` if it helps

**Comment by ZeroEkkusu** [comment]
You can try it out on any project. E.g. `forge init`:

```bash
forge build
```

- Compiles **18** files in **`1.65s`** (default)
- Compiles **18** files in **`1.65s`** (without `console` imports in `Test.sol`)
- Compiles **16** files in **`750ms`** (without `console`s imports in `Test.sol` and `Components.sol`)

Is this a Solc issue that should be reported?

**Comment by mds1** [comment]
Ah interesting, in my quick test of that sequence I still had `console2` compiled at the end (since it's used in StdUtils), but yea `console` was not compiled. I'm ok with removing `Components.sol` to improve build times, though it may be worth opening an issue in the foundry repo to see if @mattsse has any ideas, since it may be related to the build pipeline there. It's also possible named imports like this don't affect what gets compiled in the what I/we expect

**Comment by ZeroEkkusu** [comment]
Okay, let's create an issue in Foundry.

Re `console2`: You have to comment it out in `StdUtils`.

**Comment by mattsse** [comment]
builds times should have nothing to do with the forge itself, so any performance improvements are limited to solidity.

**Comment by ZeroEkkusu** [comment]
@mds1, ping someone from Solidity before proceeding?

**Comment by mds1** [comment]
> ping someone from Solidity before proceeding?

I'd suggest just opening an issue there. This is a pretty small difference in compilation speeds (compared to the via-ir issue, and relative to the total compilation time of any non-trivial repo) so would rather let them address at their leisure / normal process since I don't think this is urgent

**Comment by ZeroEkkusu** [comment]
You're right, it's not urgent.

**Comment by ZeroEkkusu** [comment]
We should remove `Components.sol` in the upcoming release to prevent the compilation of the whole library. Let's also remove the `console2` usage in `StdUtils` and instead make a private function to log the Bound Result.
