### ISSUE TITLE
UnimplementedFeatureError on solc 0.6.12 project

### ISSUE THREAD

**Issue by GokhanPolat** [foundry-rs/forge-std#240]
GM/GN friends, 
currently 'foundry' has some errors when setting it solc v0.6.12 project and getting errors like below.

> forge b
> [⠒] Compiling...
> [⠘] Compiling 15 files with 0.6.12
> [⠒] Solc 0.6.12 finished in 2.22s
> Error:
> Compiler run failed
> UnimplementedFeatureError: Nested arrays not yet implemented.

Root cause this error is forge-std library and as default forge init command pull latest libraries. If we init forge project with `--no-deps` option and then getting dependencies with git commit hash errors gonna be solve, which is I solved with 2a2ce369 commit

```shell
forge install foundry-rs/forge-std@2a2ce369
```

This pretty expectable behavior when we pull last version of dependencies.

As a result after commit forge-std v1.0.0 (#184) doesn't working with solc 0.6.

**Comment by mds1** [comment]
Adding `pragma ABIEncoder v2;` to the top of your test contract, like this, should fix it: https://github.com/foundry-rs/forge-std/blob/bb14eb04f63febf3613fdfcdd5d7a2db9063b3e5/test/compilation/CompilationTest.sol#L4

**Comment by ZeroEkkusu** [comment]
You also need to update Forge Standard to at least `v1.1.0`.
