### ISSUE TITLE
Feature request: "expectEmit" cheatcode with no arguments

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/forge-std#252]
From the Foundry Book on [best practices](https://book.getfoundry.sh/tutorials/best-practices):

> When testing events, prefer setting all `expectEmit` arguments to `true`, i.e. `vm.expectEmit(true, true, true, true)`.

My feature request is to add an `expectEmit` cheatcode that has no arguments. All of the topics (`checkTopic1`, `checkTopic2`, `checkTopic3`, and `checkData`) would be set to `true` by default.

**Comment by ZeroEkkusu** [comment]
There was `emission` in https://github.com/foundry-rs/forge-std/pull/42.

**Comment by mds1** [comment]
This idea has been discussed / gotten support in the foundry telegram a few times, so per https://github.com/foundry-rs/foundry/issues/3782 I'd support adding that cheat directly into foundry if you wanted to open the issue/PR there

**Comment by mds1** [comment]
Closed by #320
