### ISSUE TITLE
Is it possible to use `stdstore` to write to an internal mapping?

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/forge-std#264]
I tried this but it didn't work:

```solidity
stdstore.target(addr).sig("_mappingName(address)").with_key(token).checked_write(value);
```

I got the following error:

> FAIL. Reason: stdStorage find(StdStorage): No storage use detected for target.

**Comment by mds1** [comment]
The `sig` must be a public getter. It works by calling the getter, recording all slots accessed during that read, then looping through each read slot, modifying it, calling the getter again to see if we found the correct slot

Some discussion on an alternative approach to leverage storage layout instead in https://github.com/foundry-rs/foundry/issues/4022 and in the comment linked there

**Comment by paulrberg** [comment]
Thank you, @mds1.
