### ISSUE TITLE
"envOr" not working with string default values

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/forge-std#269]
The `envOr(string calldata,string calldata)` cheatcode added in #249 doesn't work:

```solidity
string memory profile = vm.envOr("FOUNDRY_PROFILE", "");
```

The following error gets thrown:

```text
Compiler run failed
error[6675]: TypeError: Member "envOr" not unique after argument-dependent lookup in contract Vm.
   --> test/BaseTest.t.sol:133:33:
    |
133 |         string memory profile = vm.envOr("FOUNDRY_PROFILE", "Foo");
    |
```

This is perhaps due to a clash with the `envOr(string calldata, bytes calldata` overload - [Solidity doesn't have great support for overloading today](https://forum.soliditylang.org/t/why-are-implicit-string-to-bytes-conversions-allowed-in-external-calls-but-not-internally/1375/).

**Comment by mds1** [comment]
The empty string `""` is ambiguous so solc isn't sure if that's string or bytes (similar to how it doesn't know if `5` is an int or uint). If you change that to `string("")` it should work

```solidity
string memory profile = vm.envOr("FOUNDRY_PROFILE", string(""));
```

**Comment by paulrberg** [comment]
Thanks @mds1, it works if I wrap the string with the `string()` constructor, but this ain't about the empty string `""`. No string would work - users always have to explicitly cast the values.

I don't think that this is a major inconvenience, but at least now there is this issue in the GitHub's history in case others bump into this problem in the future.
