### ISSUE TITLE
Suggestion to add a "v1" branch that can be used in ".gitmodules"

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/forge-std#275]
There is currently no "v1" branch in this repository that points to the latest "v1.x" release. This means that users cannot apply any ref in `.gitmodules`, because tags are not supported - only branches via the `branch` property.

[foundry-toolchain](https://github.com/foundry-rs/foundry-toolchain) has this and I think it's great for avoiding an accidental pull from `master`, which might contain bugs or might not be ready for use.

**Comment by mds1** [comment]
Just to make sure I understand: The suggestion is to add a `v1` tag that always points to the latest release. Then you can run `forge install foundry-rs/forge-std@v1` to install the latest v1.x release? And if you do that, does running `forge update lib/forge-std` automatically bump to a newer version when the v1 tag is updated?

**Comment by PaulRBerg** [comment]
Precisely - the answer to both questions is "yes".

The only maintenance cost is having to bump `v1` to point to the latest `v1.x.x` tag when it is released, but I don't think that this would be worth it.

**Comment by mds1** [comment]
> The only maintenance cost is having to bump `v1` to point to the latest `v1.x.x` tag when it is released, but I don't think that this would be worth it.

I think you mean the maintenance cost would be worth it? Sounds like you think it's not worth it 😅

Also why a v1 tag instead of a v1 branch, are there any tradeoffs there? Having a moving tag feels odd, since I think you have to force overwrite it on changes, whereas branches are intended to change. Seems the guidance in https://github.com/actions/javascript-action#create-a-release-branch is to use a branch (I know foundry-toolchain uses a tag instead of a branch, not sure why though)

**Comment by PaulRBerg** [comment]
> I think you mean the maintenance cost would be worth it?

haha lol, yeah, meant to say without "don't" (I have it stricken out).

> Also why a v1 tag instead of a v1 branch

Again, I meant to say branch, not a tag. I actually opened an issue about this yesterday - for some reason, [Forge sets the installed submodule's latest release tag as a `branch` in the `.gitmodules`](https://github.com/foundry-rs/foundry/issues/4155), but it shouldn't.

Lots of mistakes on my part in this issue - thanks for correcting them.

**Comment by mds1** [comment]
Got it! Just created a `v1` branch, lmk how this looks: https://github.com/foundry-rs/forge-std/tree/v1

**Comment by PaulRBerg** [comment]
Perfect, thanks.

**Comment by PaulRBerg** [comment]
@mds1 [v1.4.0](https://github.com/foundry-rs/forge-std/releases/tag/v1.4.0) has just been released, but the `v1` branch has not been updated.

**Comment by mds1** [comment]
Oops thanks for the reminder, should be good now!
