### ISSUE TITLE
Release 1.3.0 missing 1.3.0 version number bump in package.json

### ISSUE THREAD

**Issue by relyt29** [foundry-rs/forge-std#281]
Idk if you want to amend the commit, but you forgot to bump the version number in the package.json

**Comment by mds1** [comment]
Thanks for catching this! There will be a v1.4.0 soon (see #282), so I'll just skip to v1.4.0 at that time and leave this issue open until then. Does that work, or does this currently break anything for node/hardhat users?

**Comment by relyt29** [comment]
I don't know but it doesn't break anything for our company, just was a weird fluke I noticed while updating the version
