### ISSUE TITLE
"InvariantTest" does not have a "vm" 

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/forge-std#282]
No cheatcodes can currently be used in a test contract that inherits just from [`InvariantTest`](https://github.com/foundry-rs/forge-std/blob/0aa99eb8456693c015350c5e6c4f442ebe912f77/src/InvariantTest.sol).

I don't know if this is intended - but if it is, we should definitely mention what's the recommend way of adding the `vm` (in https://github.com/foundry-rs/book/pull/760), e.g. inherit from `Test`, or `TestBase`, define a `vm` yourself, etc.

**Comment by mds1** [comment]
You would inherit from both, e.g. `MyInvariantTest is Test, InvariantTest`. The latter just adds some invariant helper methods to your contract. Now that I think of it, I wonder if the content of `InvariantTest` should just be part of `Test` by default, wdyt? cc @gakonst @lucas-manuel for thoughts too

**Comment by lucas-manuel** [comment]
I think since invariants are a subset of overall testing it makes sense to do `Test, InvariantTest`. However if this is something that people will run into often I can see the argument for adding both the `Test` though. 

Comes down to compilation time vs. ease of use I guess. What do you think is best here @mds1?

**Comment by PaulRBerg** [comment]
> Now that I think of it, I wonder if the content of `InvariantTest` should just be part of `Test` by default, wdyt?

Works for me.

> Comes down to compilation time vs. ease of use

Compilation times should not be a concern in this case - compiling a dozen or so functions should be a super quick task on modern computers.

**Comment by PaulRBerg** [comment]
Another benefit of merging `InvariantTest` with `Test` is that it would partially address this issue:

https://github.com/foundry-rs/foundry/issues/4162

That is, invariant tests would no longer be considered something qualitatively different from fuzz tests - which makes sense, since inputs are fuzzed in invariants tests, too.

**Comment by gakonst** [comment]
Let's do `contract Test is InvariantTest` then?

**Comment by mds1** [comment]
I'm good with that. This would be a breaking change, so we'll release a v1.4.0 after?

**Comment by gakonst** [comment]
SGTM.

**Comment by Sabnock01** [comment]
Shouldn't the invariant testing utilities follow the same pattern as everything else? 

i.e. have the file `StdInvariant.sol` inherited by `Test.sol`?

**Comment by mds1** [comment]
> i.e. have the file `StdInvariant.sol` inherited by `Test.sol`?

Yea this is what I was planning to do actually, will open a PR for it sometime this week

**Comment by mds1** [comment]
PR for this is ready [here](https://github.com/foundry-rs/forge-std/pull/292) if anyone can give a quick review 🙂
