### ISSUE TITLE
Make `CREATE2_FACTORY` internal (instead of private)

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/forge-std#285]
Here:
https://github.com/foundry-rs/forge-std/blob/4a79aca83f8075f8b1b4fe9153945fef08375630/src/StdUtils.sol#L24

With access to `CREATE2_FACTORY` in tests, I could do:
```solidity
vm.prank(CREATE2_FACTORY);
Contract c = new Contract{salt:""}(...args);
```

which would be much nicer than the current alternative: 
```solidity
bytes memory initCode = hashInitCode(type(Contract).creationCode,abi.encode(...args));
address ac = computeCreate2Address("",initCode);
``` 
About the above: 
1. it is more cumbersome, and 
2. it does not have the nice side-effect of actually creating an instance of `Contract`.

**Comment by mds1** [comment]
I think the right fix here is in `Base.sol`, moving `CREATE2_FACTORY` out of `ScriptBase` and into `CommonBase`, that way it's present in both `Test` and `Script`. Feel free to open a PR for that
