### ISSUE TITLE
StdChains initialize function name conflict

### ISSUE THREAD

**Issue by ind-igo** [foundry-rs/forge-std#286]
This is more of a nice-to-have suggestion, but the function `initialize` in StdChains.sol is in conflict with a few of our deploy scripts after an update of forge-std. We have changed our function name, but imo the use of the word `initialize` is very common for contract deployments and it would make sense for StdChains.sol to use an adjacent name to free this keyword up for implementations. Would suggest something like `initializeChain` or something similar.

**Comment by mds1** [comment]
Huh interesting, even though the `initialize` function in `StdChains` is private, it still causes a collision. Didn't realize that

If you want to submit a PR to rename to `initializeStdChains()` that seems good with me!
