### ISSUE TITLE
chore: update `StdJson.sol` to use the specific JSON parsing cheats

### ISSUE THREAD

**Issue by mds1** [foundry-rs/forge-std#288]
For example, the current `readUint` helper is like this:

```solidity
function readUint(string memory json, string memory key) internal pure returns (uint256) {
    return abi.decode(vm.parseJson(json, key), (uint256));
 }
```

But I think it should be:

```solidity
function readUint(string memory json, string memory key) internal pure returns (uint256) {
    return vm.parseJsonUint(json, key);
 }
```

@odyslam can you confirm that we should make this change / implement it if you have time?

**Comment by odyslam** [comment]
Yes, should be done some time towards the end of next week. Thanks for bringing this up to my attention :)

**Comment by mds1** [comment]
Thanks @odyslam! Would love to get the v1.4.0 release out this week + include this change in that if we can
