### ISSUE TITLE
Transactions in test cases do not consume gas

### ISSUE THREAD

**Issue by rayzhudev** [foundry-rs/forge-std#296]
# Description

I have looked, and haven't been able to find a way for forge to consume gas on transactions in tests? 
e.g. I expect
```
function testFoo() public {
	uint256 aliceBalance = 0xAlice.balance;
	vm.prank(0xAlice);
	contract.foo();

	assertLt(0xAlice.balance, aliceBalance);
}
```

I want Alice's balance to be deducted the gas cost of the transaction. Right now this is not the case. My suggestion is to add a cheatcode that enables this.

# Why

I'm testing a function which is dependent on block.basefee and the gas cost of the transaction but I can't tell whether the function is working correctly because the caller isn't paying anything for transaction cost. I've been able to set the basefee using the cheatcode vm.fee(100 gwei) but that useless given that gas isn't being paid for transactions anyways.

----- 

If anyone can provide a solution to this scenario, I'd greatly appreciate it. In the meantime, I used hardhat to test it because transactions in hardhat consume gas.

**Comment by mds1** [comment]
By default the gas price is zero, but you can change this by invoking `forge test` using the `--gas-price` and `--block-base-fee-per-gas` flags.

**Comment by rayzhudev** [comment]
@mds1 I tried using those flags but there was still no gas being consumed by the caller's balance. I tested it and the gas price and base fee were being set, but the transactions still didn't deduct anything from the balance. Could you show me how you got it to work with running code similar to what I have above?

**Comment by mds1** [comment]
Ahh interesting I think that makes sense, since the full test is really a single tx. I'm not sure how you'd do this / if it's supported, so I'd recommend closing this issue and re-opening it in the foundry repo (since it really is a foundry issue, not forge-std) and seeing what they say there 🙂

**Comment by mds1** [comment]
Closing per the above comment, since this is not a forge-std issue
