### ISSUE TITLE
Rename `makeAddr()` to `makeAddress()`

### ISSUE THREAD

**Issue by vbidin** [foundry-rs/forge-std#297]
This refers to the following two functions from [StdCheats.sol](https://github.com/foundry-rs/forge-std/blob/master/src/StdCheats.sol#L402-L412) which look out of place next to their more verbose brethren:
- `makeAddr()` -> `makeAddress()`
- `makeAddrAndKey()` -> `makeAddressAndKey()`

**Comment by mds1** [comment]
This naming is consistent with the `vm.addr` cheat upstream. Renaming would be a breaking change, and it's easy to introduce a `makeAddress` alias in your own code, so I'm going to close this 🙂
