### ISSUE TITLE
Thoughts on a new cheat like `deal` that does not overwrite the current balance?

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/forge-std#298]
My feature request is about the `deal` cheat codes:

https://github.com/foundry-rs/forge-std/blob/662ae0d6936654c5d1fb79fc15f521de28edb60e/src/StdCheats.sol#L540-L571

Overwriting the current balance works for standard tests, but it is not helpful in an invariant testing context. Certain invariant may rely upon the contract balance over time.

Thus my suggestion to add a new cheat like `deal` but which is additive, which adds the provided amount on top of the current balance.

This is for both ETH and ERC-20 tokens.

**Comment by mds1** [comment]
This is really just a one liner that removes a `balanceOf` call—i.e. you can currently do this with `deal(token, to, token.balanceOf(to) + amount)`, which is pretty brief and clear—so I'm not sure it adds much value

**Comment by PaulRBerg** [comment]
Fair enough.
