### ISSUE TITLE
Add `excludeSelector` to `StdInvariant`

### ISSUE THREAD

**Issue by horsefacts** [foundry-rs/forge-std#299]
Most of the invariant test filtering helpers have both `target` and `exclude` variants to include or filter contracts/senders/selectors from fuzzing. But there's no corresponding `excludeSelector` for `targetSelector`. It's probably a safer practice to start by _excluding_ selectors from a handler contract to avoid forgetting a function or two for large handlers, so it would be useful to have `excludeSeclector`.

(Secondarily, the naming of `targetSelector` seems a little odd. It's singular, but the function accepts multiple selectors for a single contract address. It might be clearer as `targetSelectors`/`excludeSelectors` plural. I did a double take as I wrote this up, worried that I got it wrong in my examples!)

**Comment by mds1** [comment]
@mattsse do you mind transferring this to the foundry repo since `excludeSelector` would be a change to forge itself? (or @horsefacts feel free to close and reopen there, sorry for the confusion)

**Comment by horsefacts** [comment]
Ah, whoops. I'll move it!

**Comment by horsefacts** [comment]
Reopened on forge as https://github.com/foundry-rs/foundry/issues/4352
