### ISSUE TITLE
forge `fmt` error with 0.8.18-supported named mapping params

### ISSUE THREAD

**Issue by z0r0z** [foundry-rs/forge-std#309]
ParserError, message: "unrecognised token ..."

**Comment by mds1** [comment]
This should have been resolved per https://github.com/foundry-rs/foundry/issues/4319 / https://github.com/foundry-rs/foundry/pull/4328, so make sure you're on the latest forge version. This is also not a forge-std issue, so going to close, but if you're still seeing this feel free to open an issue in the foundry repo
