### ISSUE TITLE
vm expect revert , not reverted as expected

### ISSUE THREAD

**Issue by MiguelBits** [foundry-rs/forge-std#323]
I have faced this issue in a lot of my projects..
https://github.com/MiguelBits/Y2K_Earthquake/blob/6f42d7e52f2ad11b14b3fe09a7e1286dbc641d57/test/VaultTest.t.sol#L172
I have to comment this line and make testFail instead of just test.
Sometimes it works, for example here: https://github.com/MiguelBits/Y2K_Earthquake/blob/6f42d7e52f2ad11b14b3fe09a7e1286dbc641d57/test/VaultTest.t.sol#L143

But most of the times, it does not, even when copy pasting the error message params to the expected revert

**Comment by mds1** [comment]
In the first test you linked, if you uncomment the `exectRevert` you have:

```solidity
vm.startPrank(ADMIN);
vm.expectRevert(Vault.AddressZero.selector);
vaultFactory.changeController(vaultFactory.marketIndex(), address(0));
vm.stopPrank();
```

`vm.exectRevert` applies to the next call. In this case, that is the `vaultFactory.marketIndex()` call which is executed before the `vaultFactory.changeController()` call. You can fix this by modifying your test like this:

```solidity
uint256 index = vaultFactory.marketIndex();
vm.prank(ADMIN); // Order of `prank` and `expectRevert` shouldn't matter
vm.expectRevert(Vault.AddressZero.selector);
vaultFactory.changeController(index, address(0));
```

**Comment by MiguelBits** [comment]
thank you so much
