### ISSUE TITLE
unable to parse mnemonic in French

### ISSUE THREAD

**Issue by vjuge** [foundry-rs/forge-std#325]
Hello,

using a mnemonic like:
`rugueux véloce régulier prairie ....`

running following solidity code:
```solidity
string memory mnemonic = vm.envString("MNEMONIC");
address deployer = vm.addr(vm.deriveKey(mnemonic, 0));
        
```

I get the following : 

```solidity 
[FAIL. Reason: the word `rugueux` is invalid] testAccount() (gas: 7518)
Traces:
  [7518] Mangrove::testAccount() 
    ├─ [0] VM::selectFork(0) 
    │   └─ ← ()
    ├─ [0] VM::envString(MNEMONIC) [staticcall]
    │   └─ ← <env var value>
    ├─ [0] VM::deriveKey(<pk>) [staticcall]
    │   └─ ← "the word `rugueux` is invalid"
    └─ ← "the word `rugueux` is invalid"

````

Is there a way to specify language pack to use ?

FYI tested with the same mnemonic and ethersjs/hardhat, is working fine (despite ethersjs may require to specify the language pack)

**Comment by mds1** [comment]
cc @mattsse, can you transfer this to the foundry repo? I don't have permissions to

**Comment by vjuge** [comment]
@mds1, @mattsse no pb I'll duplicate it to the foundry repo, and cancel this one
