### ISSUE TITLE
[Invariant Tests] Unable to stop targeting contracts deployed during function calls

### ISSUE THREAD

**Issue by 3s-joaolopes** [foundry-rs/forge-std#334]
Hey, during invariants tests, it seems that contracts deployed during the random function calls are automatically added to the _targetedContracts array. Is this expected behavior ? By looking into the [foundry book](https://book.getfoundry.sh/forge/invariant-testing) it seems that only contracts that are deployed during setUp and contracts manually added to the targetContracts array should be targeted, but this is not the behavior I'm observing.

During setUp I'm just deploying a handler contract and using the functions targetSelector() and targetSelector() to specify the address and functions I want the test to target. This works for the first random call, but after that the _targetedContracts is overridden to include all the contracts deployed during the first random call. 
Is there a way to exclude these new contracts from the _targetedContracts array?

Note: I don't want to deploy the contracts during the setUp stage, as I want the number of contracts deployed (and some of their parameters) to be random, so I'm basically deploying them on the first random function call in the test.

**Comment by mds1** [comment]
This is the expected behavior—contracts deployed during your invariant test are automatically added to the list of potential targets. To exclude them, you can use [`excludeArtifact`](https://github.com/foundry-rs/forge-std/blob/46264e9788017fc74f9f58b7efa0bc6e1df6d410/src/StdInvariant.sol#L34-L36)
