### ISSUE TITLE
Option to hide the bound logs

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/forge-std#349]
The `bound` utility logs the bound result:

https://github.com/foundry-rs/forge-std/blob/fc560fa34fa12a335a50c35d92e55a6628ca467c/src/StdUtils.sol#L80

This is useful, but in fuzz tests it can be annoying because it clutters the console output with "Bound Result" lines, e.g. from a recent test I wrote:

<img width="365" alt="Screenshot 2023-04-13 at 12 47 32 PM" src="https://user-images.githubusercontent.com/8782666/231722382-5f1f8041-b7d7-4294-a566-0c34fd4df700.png">

It would be nice if users had the option to disable the logs, e.g. with an overloaded version of `bound` that takes a boolean as a fourth parameter.

**Comment by PaulRBerg** [comment]
Another example from CI:

<img width="1329" alt="Screenshot 2023-04-14 at 1 11 37 PM" src="https://user-images.githubusercontent.com/8782666/232016812-b3899837-71ba-4d6e-ad56-1abc1ea8f43f.png">

**Comment by mds1** [comment]
For uints, there is `_bound` which does not have the logs. I'd also be supportive of a `quietBound` method or `bound` with a bool overload because I agree it can sometimes be too noisy

**Comment by PaulRBerg** [comment]
I missed `_bound` - that works well for my needs. In this case, I don't think providing another alias (i.e. `quiteBound`) would be worth it. `_bound` is good.

I created a PR to provide an equivalent silent `_bound` for the integer variant: https://github.com/foundry-rs/forge-std/pull/350

In future major versions of Forge Std, we should consider renaming `_bound` to something like `silentBound`, to provide more clarity on the difference between `bound` and `_bound`.

**Comment by mds1** [comment]
Agreed it could use a better name. Offhand I don't recall why we originally extracted the console.log into `bound` vs `_bound` (it's somewhere in a PR discussion) but IIRC it wasn't intended for devs to use, hence the underscore as opposed to `quietBound` or `silentBound`.

Going to mark this as closed by https://github.com/foundry-rs/forge-std/pull/350. Also made a note of this in https://github.com/foundry-rs/foundry/issues/3782#issuecomment-1512948087
