### ISSUE TITLE
feat: check for successful deploy in `deployCode`

### ISSUE THREAD

**Issue by mds1** [foundry-rs/forge-std#35]
`create` (and `create2`, though it's not used) return the zero address if a deploy fails. The `deployCode` helpers should have a check such as:

```solidity
require(addr != address(0), "Deployment failed. Ensure the artifact path and file contents are correct.")
```

**Comment by mds1** [comment]
Just reread this. There are definitely more causes of reasons this can fail aside from those two, so maybe just `Deployment failed` as the error message

**Comment by mds1** [comment]
Just want to clarify in case anyone picks this up, since the format and example seem to differ a bit. I'd personally suggest:

```
require(condition, "ContractName (functionName): Error message here.");
```

In other words, no underscores in the require statements. Alternatively, we could do functionSig (e.g. `deal(address,uint256)`) instead of functionName (e.g. `deal`) to help disambiguate overloaded functions.

**Comment by dsam82** [comment]
@ZeroEkkusu just have to check for `zero` address reverts, right?

Should I add tests for failures as well?

**Comment by ZeroEkkusu** [comment]
@dsam82 Yes. Will you also standardize the other error messages?

I'd suggest this format based on Matt's suggestions:

```solidity
require(condition, "ContractName functionName(type,type): Error message here.");
```

> Should I add tests for failures as well?

Yes, please.

**Comment by dsam82** [comment]
Ok, will do that.

**Comment by dsam82** [comment]
I had an idea of creating a simple reverting contract and then using `deployCode` to check for zero address reverts. 

Currently encountering an error: `expectRevert` is not working even though revert is being thrown. 

Will create a draft PR soon.
