### ISSUE TITLE
Commit VSCode settings in version control

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/forge-std#351]
Forgetting to run `forge fmt` is a frequent source of error for CI failures in PRs.

@mds1 - what do you think about committing a minimal set of VSCode settings in version control, so that VSCode users get auto-formatting on save?

e.g.

```json
{
  "[solidity]": {
    "editor.defaultFormatter": "NomicFoundation.hardhat-solidity"
  },
  "editor.formatOnSave": true,
  "solidity.formatter": "forge"
}
```

**Comment by PaulRBerg** [comment]
Alternatively, we could use [`JuanBlanco.solidity`](https://marketplace.visualstudio.com/items?itemName=JuanBlanco.solidity). I don't mind either way.

**Comment by mds1** [comment]
I'm personally not a fan of adding IDE specific settings to repos for a few reasons, mainly that (1) not everyone uses VSCode, and (2) of those that do, not all of them use the same solidity extension. In the past to make things easier for contributors I'll just fix the fmt issues myself before merge so I think the current approach seems ok :)
