### ISSUE TITLE
Add `vm.pubKey(uint)(uint,uint)` cheatcode to `Vm.sol`

### ISSUE THREAD

**Issue by pmerkleplant** [foundry-rs/forge-std#356]
`Vm.sol` provides a function to receive the address of a private key: `addr(uint256)(address)`.
Could we get a function to receive the public key as well? 

The public key is a secp256k1 point and should be returned in Affine coordinates, i.e. `(unit x_coordinate, uint y_coordinate)`.

To receive the public key of a private key, you currently either have to implement an `ecMul` function in solidity, quickly leading to out-of-gas errors or use `ffi`, leading to big overhead and long-running testsuites.

**Comment by mds1** [comment]
This makes sense. Can you reopen this issue in the foundry repo and close this one (I don't have permission to transfer the issue), since this would require a new cheat in forge upstream first since currently there's no cheat to do this

**Comment by pmerkleplant** [comment]
Opened issue in foundry, see https://github.com/foundry-rs/foundry/issues/4790.
Closing, and many thanks ^^
