### ISSUE TITLE
Add new reset Nonce cheatcodes

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/forge-std#390]
ref https://github.com/foundry-rs/foundry/pull/5033

**Comment by joaquinlpereyra** [comment]
@mattsse Is it OK if I do it in the same PR that adds `destroyAccount` as a higher-level cheatcode? https://github.com/foundry-rs/forge-std/pull/389

**Comment by joaquinlpereyra** [comment]
I've gone ahead and did that, just added a new small commit to #389.

**Comment by mds1** [comment]
Closed by https://github.com/foundry-rs/forge-std/pull/389
