### ISSUE TITLE
code.length

### ISSUE THREAD

**Issue by veridelisi** [foundry-rs/forge-std#397]
Hello
There is  code.length in foundry exercises .  What does it mean exactly?
For example
any address.code.length returns 118
sincerely
VeriDelisi

**Comment by mds1** [comment]
That is the number of bytes of code at that address. `address(x).code` returns a `bytes memory` variable with the code at the address, and `address(x).code.length` returns the length of those bytes

**Comment by veridelisi** [comment]
What does it mean 118?

**Comment by mds1** [comment]
118 bytes, please see the solidity docs or https://www.evm.codes/#3b?fork=shanghai for more info

**Comment by veridelisi** [comment]
There is no information in the evm playground.
118 is gas cost?

**Comment by mds1** [comment]
If `address(x).code.length` returns a value of 118 it means the code at `address(x)` is 118 bytes in length. I recommend reading the solidity docs and some introductory EVM material :)
