### ISSUE TITLE
Error : Member "startBrodcast" not found or not visible after argument-dependent lookup in contract Vm.

### ISSUE THREAD

**Issue by devansh-m12** [foundry-rs/forge-std#428]
i am getting this error
```
Member "startBroadcast" not found or not visible after argument-dependent lookup in contract Vm.
```
while executing my code:
``` solidity
function run () external returns (FundMe) {
        vm.startBrodcast();
        FundMe fundMe = new FundMe();
        vm.stopBroadcast();
        return fundMe;
    }
'''

i imported forge as instructed in manual is there any issue with startBroadcast funtion ?

**Comment by mds1** [comment]
Make sure you are using the latest forge-std version and have your script configured correctly (it should inherit from forge-std's `Script` contract. If you still need help debugging, please share a repo to reproduce with :)

**Comment by Sabnock01** [comment]
@devansh-m12 did this solve your issue?

**Comment by devansh-m12** [comment]
@Sabnock01 yes , I had to reinstall the forge

**Comment by mds1** [comment]
Glad it’s resolved! I’ll close this issue now :)
