### ISSUE TITLE
Issue for the typed loggin

### ISSUE THREAD

**Issue by jjhesk** [foundry-rs/forge-std#455]
When have a struct output from a function like that 
```


interface Project {
    struct Info {
        uint256 timestamp;
        uint256 amount;
    }
}
    function withdrawInfo(address account)
        external
        view
        returns (Project.Info[] memory);
```
I have 2 options to log in console:
1. convert the bytes into array and log them as array bytes but there is no such thing called `console.logBytesArray`
2. convert these into json format and log them as there is no helper solution.

What is the best way to log these of bytes?

If there are more forgivable object logging solution like python does that will make documenting the result log more readable and less coding.

**Comment by mds1** [comment]
There's no standard best way—solidity does not have generics so you can't have a general logging solution like other languages, instead you need a bespoke method for each type. I'd suggest writing your own helper methods like this:

```solidity
function printProjectInfo(Project.Info memory info) internal {
  // Print the struct however you want, for example log each field:
  console2.log("info.timestamp", info.timestamp);
  console2.log("info.amount   ", info.amount);
}

function printProjectInfo(Project.Info[] memory info) internal {
  for (uint256 i = 0; i < info.length; i++) {
    console2.log(string.concat("item ", vm.toString(i)));
    printProjectInfo(info[i[);
  }
}
