### ISSUE TITLE
feature reqest

### ISSUE THREAD

**Issue by jjhesk** [foundry-rs/forge-std#457]
In the mix of off chain and on-chain, is that possible to select some off-chain valuables that can trigger directly with some code like python or js with vm executions?

some ideas with some vm executions
```
vm.bash("path-file command")
vm.python("path-file command")
vm.js("path-file command")
```

**Comment by brockelmore** [comment]
this is possible via `ffi` cheatcode. One option would be to create a nice wrapper for common programs, but imo that is out of the scope of forge-std

**Comment by mds1** [comment]
Yep, this can be done with `vm.ffi` and `vm.tryFfi`, so closing this :)
