### ISSUE TITLE
Feature request: details of errors encountered during setUp()

### ISSUE THREAD

**Issue by 0xJem** [foundry-rs/forge-std#476]
Debugging what is causing an error during the `setUp()` function in a test is quite difficult, given that this is the output (with `-vvv`):
```
Running 1 test for src/test/policies/Bonds/BondCallback.t.sol:BondCallbackTest
[FAIL. Reason: setup failed: custom error 11bf00c9:0000000000000000000000009ed3181af46a7fc01e818d3461c222e8e39b63d3] setUp() (gas: 0)
Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 7.88ms
```

**Comment by mds1** [comment]
To show `setUp` traces you will need to increase the verbosity to `-vvvv`, see https://book.getfoundry.sh/forge/tests#logs-and-traces
