### ISSUE TITLE
feat: upstream Solmate's `bound`

### ISSUE THREAD

**Issue by mds1** [foundry-rs/forge-std#48]
This method is useful for wrapping inputs of a fuzz test into a certain range, and t11s has given approval to upstream this. Scope:
- Add [`bound`](https://github.com/Rari-Capital/solmate/blob/9f16db2144cc9a7e2ffc5588d4bf0b66784283bd/src/test/utils/DSTestPlus.sol#L115-L136)
- Add the associates [tests](https://github.com/Rari-Capital/solmate/blob/main/src/test/DSTestPlus.t.sol)
    - Add `bound` tests that cover `type(uint256).max` as the upper bound input, since this is an edge case handled separately within `bound`
    - Change the `testFail` tests to the `expectRevert` style

I don't plan on working on this over the next few days, so this is open for anyone to take 🙂

**Comment by ZeroEkkusu** [comment]
Opened an issue from `assertApproxEqRel`, `assertApproxEqAbs` tests here #49

**Comment by mds1** [comment]
Thanks! Just updated description to remove that

**Comment by ZeroEkkusu** [comment]
Cc @OliverNChalk see Matt's comment.

**Comment by sscobes** [comment]
Hey, I was able to make the additions for this issue.
