### ISSUE TITLE
strange behaviour with stdJson.serialize: Error: Yul exception:Variable ... is ... too deep in the stack

### ISSUE THREAD

**Issue by AlcibiadesCleinias** [foundry-rs/forge-std#488]
Hi,

First of all, I am sorry, that I did not dig into the problem and can not address it better than showing the case where I faced **a mem stack limit** in comparison to where the error is not occurring during the sol compilation of the **Foundry script**.

The **strange behavior** is about how I hack the issue.

# Requirement
I am using Foundry and work with the solidity code, thus Foundry should be installed. Also I am used to use **makefile**.

# Reproduce Bug
To face with issue:

1. Clone the repo https://github.com/fluencelabs/deal and `git checkout show-stack-problem`
2. Run `make build-contracts`
3. it throws with `Error: Yul exception:Variable _1 is 1 too deep in the stack` during compiling the foundry script file: https://github.com/fluencelabs/deal/blob/show-stack-problem/script/Deploy.s.sol (do not waste your time nd start to analyse the script code, merely continue read below, as I believe it could give you better overview of the issue)

> From here it seems that I have a standard exception of exiting the limit of a stack of solidity EVM. But, let me show the below hack:

# Strange Dirty Hack Solution

1. Checkout to branch with the hack: `git checkout show-no-stack-problem`
> on that moment here is the  diff: https://github.com/fluencelabs/deal/compare/show-no-stack-problem...show-stack-problem?expand=1

2. Run `make build-contracts`
3. Compiled successfully.

Compiled successfully but at what price?

PS. As I did not give a good amount of attention to the bug during the work, it is possible that I addressed the issue in the wrong place (https://github.com/foundry-rs
/[forge-std](https://github.com/foundry-rs/forge-std)). Please, patiently address me in that case and take my apologies.

**Comment by mds1** [comment]
This is a solidity issue, not a forge-std issue, so going to close this. There are various ways to resolve stack too deep errors, such as scoping with `{` `}` braces, moving variables into structs, breaking things into smaller functions, or using via-ir
