### ISSUE TITLE
Error: No arguments passed to the base constructor.

### ISSUE THREAD

**Issue by F4r84D** [foundry-rs/forge-std#495]
Hello,

I'm in the process of deploying an NFT contract on the Anvil testnet, as outlined in the Solidity scripting documentation [here](https://book.getfoundry.sh/tutorials/solidity-scripting). However, I've encountered a constructor error. Could you please guide me on how to pass arguments to the base constructor to resolve this issue?

Thank you.
![Forgex1x1x1](https://github.com/foundry-rs/forge-std/assets/38158729/6328ffef-e1f6-425f-8f62-c5a7532db7e6)

**Comment by mds1** [comment]
This is an error from solidity, please read the solidity docs. In particular: https://docs.soliditylang.org/en/latest/contracts.html#inheritance
<img width="606" alt="image" src="https://github.com/foundry-rs/forge-std/assets/17163988/22104875-7133-494d-b3af-242c9190adcd">
