### ISSUE TITLE
ENV var incorrectly takes precedence over CLI flag

### ISSUE THREAD

**Issue by 0xCLARITY** [foundry-rs/forge-std#509]
I was running into an issue with running:

```
forge script ... \
          --etherscan-api-key XYZ \
          --verify
```

I kept getting told I had an invalid API Key - when I knew what I was passing was correct.

The issue was I had an `ETHERSCAN_API_KEY` defined in my environment, and so the CLI flag was being ignored. This was unexpected behavior to me, as I would have expected any CLI flags to take precedence over environment variable defaults.

**Comment by sambacha** [comment]
Env is supposed to take precedence over CLI. ENV is not stored on the heap, nor is there a global variable in the data section pointing to it. The environment is stored entirely on the stack and is a part of the initial process stack that is set up before the program starts running. Ergo, it takes precedence.
