### ISSUE TITLE
Native String Cheatcodes Not Present

### ISSUE THREAD

**Issue by tynes** [foundry-rs/forge-std#519]
The cheatcodes implemented in the following [PR](https://github.com/foundry-rs/foundry/pull/6891) are not yet in forge-std. Is nobody using them yet?

They are:
 - toLowercase
 - toUppercase
 - trim
 - replace
 - split

**Comment by mds1** [comment]
People may be using them with a manually patched `Vm` interface. These cheats should automatically get added as part of #518, and once that is merged I'll finally put put the v1.8.0 release that also includes #514, cc @klkvr so you're aware

**Comment by mds1** [comment]
These are now implemented in v1.8.0 https://github.com/foundry-rs/forge-std/releases/tag/v1.8.0
