### ISSUE TITLE
meta: usefulness of a Strings/Bytes utils in forge-std?

### ISSUE THREAD

**Issue by dmfxyz** [foundry-rs/forge-std#52]
Forge's `ffi` cheatcode accepts an array of strings. This generally works well for passing shell commands, but becomes troublesome when those commands have to include data or arguments represented by solidity variables.

Other than [OpenZeppelin's Strings library](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Strings.sol), which only handles `uint`s, I am not aware of any other common String conversion libraries. Most solutions are home grown. 

If FFI grows in popularity, it might be helpful to expose a library that helps with the conversion back and forth between strings consumable by non-evm Web3 libraries and EVM variables. For example, if you want to pass a `bytes memory` array to FFI, you need to implement your own function like this (copied from the differential testing tutorial):

```solidity
library Strings2 {

    ///@dev converts bytes array to its ASCII hex string representation
    /// TODO: Definitely more efficient way to do this by processing multiple (16?) bytes at once
    /// but really a helper function for the tests, efficiency not key.
    function toHexString(bytes memory input) public pure returns (string memory) {
        require(input.length < type(uint256).max / 2 - 1);
        bytes16 symbols = "0123456789abcdef";
        bytes memory hex_buffer = new bytes(2 * input.length + 2);
        hex_buffer[0] = "0";
        hex_buffer[1] = "x";

        uint pos = 2;
        uint256 length = input.length;
        for (uint i = 0; i < length; ++i) {
            uint _byte = uint8(input[i]);
            hex_buffer[pos++] = symbols[_byte >> 4];
            hex_buffer[pos++] = symbols[_byte & 0xf];
        }
        return string(hex_buffer);
    }
}
```

There are likely other examples as well. Opening up here for discussion to see if others think it's worth including a library, and if so what features we would want to support.

**Comment by mds1** [comment]
@gakonst What would be involved in making `ffi` more user friendly so it can e.g. handle the ABI encoding/decoding for you? Not sure how feasible that is.

My main hesitation is that this is a good stopgap but hard to get perfect. Main example I can think of is ffi'ing to a script that takes an address input. The only libs I've seen will convert addresses to hex strings by going through uint, so leading zeros on your address get truncated. You can of course account for that in your script, but that's still tedious/bad UX.

So wondering if forge-std is the right place to fix this vs. improving ergonomics of the cheat-code then perhaps having forge-std overloads to improve UX?

**Comment by gakonst** [comment]
I think let's gather some more examples of people struggling with FFI?

Then we could:
1. Add more ways to call FFI in Foundry EVM (similar to how we allow overloading of vm.expectRevert)
2. Add wrappers which internally do abi.encode / abi.decode to forge-std

But before we know how people use it we're flying blind

**Comment by dmfxyz** [comment]
Makes sense. I have seen 1-2 other repos implementing this bytes conversion, but nothing else so far. Will post other examples to this thread as I encounter them.

**Comment by mds1** [comment]
Is this issue now obsolete due to `vm.toString`, or is there something else needed to close this?

**Comment by dmfxyz** [comment]
Obsolete! Closed.
