### ISSUE TITLE
`DSTest` removal in v1.8.0 seems to break the `forge` contract sizer filter

### ISSUE THREAD

**Issue by CruzMolina** [foundry-rs/forge-std#522]
Bumping from v1.7.6 to v1.8.0 seems to break the way `forge build --sizes` filters out test contracts.

Test contracts that import & inherit `forge-std/Test.sol` now appear in the `forge build --sizes` output.

**Comment by mds1** [comment]
Thanks for reporting! Fixed in https://github.com/foundry-rs/forge-std/releases/tag/v1.8.1
