### ISSUE TITLE
Change `vm` visibility to internal in `StdAssertions` and `StdUtils`

### ISSUE THREAD

**Issue by smol-ninja** [foundry-rs/forge-std#530]
Currently, the visibility of `vm` in `StdAssertions` and `StdUtils` is private which means it cannot be use by the derived contract.

https://github.com/foundry-rs/forge-std/blob/bb4ceea94d6f10eeb5b41dc2391c6c8bf8e734ef/src/StdAssertions.sol#L8

https://github.com/foundry-rs/forge-std/blob/bb4ceea94d6f10eeb5b41dc2391c6c8bf8e734ef/src/StdUtils.sol#L17

If we change it to internal, `vm` can be used directly with StdAssertions and StdUtils imports.

**Comment by mds1** [comment]
This will cause a solc `Identifer already declared` error because we define `vm` as internal in `CommonBase` which is used by `Test` and `Script`. If you don't want to inherit from  `Test` and `Script` you can instead inherit from `CommonBase`

**Comment by smol-ninja** [comment]
Thank you @mds1 for your comment. That solves it.
