### ISSUE TITLE
Package.json version is not updated.

### ISSUE THREAD

**Issue by firattale** [foundry-rs/forge-std#534]
The version is outdated in the package.json, it should be compatible to latest release. 
1.7.6 => 1.8.1

**Comment by mds1** [comment]
Thank you, I will fix this with the next release

**Comment by ChiTimesChi** [comment]
@mds1 is there a timeline for the next release? This is causing cache issues when `forge-std` is installed using npm.

**Comment by mds1** [comment]
Planning to get the release out this week!

**Comment by mds1** [comment]
Just released v1.8.2 https://github.com/foundry-rs/forge-std/releases/tag/v1.8.2
