### ISSUE TITLE
Can't seem to read `CallerMode` from `vm.readCallers()`

### ISSUE THREAD

**Issue by brickpop** [foundry-rs/forge-std#561]
I must be missing something but I am trying to call `vm.readCallers()` and there is no way to receive the first parameter of the result's tuple. 

```solidity
pragma solidity ^0.8.17;
import {VmSafe} from "forge-std/VM.sol";

function blah() {
        VmSafe.CallerMode initialMode;
        address initialSender;
        address dummy;
        (initialMode, initialSender, dummy) = vm.readCallers(); // compiler error

        // In-place declaration, same issue
        (VmSafe.CallerMode initialMode, , ) = vm.readCallers(); // compiler error
}
```

Output:
```
Compiler run failed:
Error (7407): Type tuple(enum VmSafe.CallerMode,address,address) is not implicitly convertible to expected type tuple(enum VmSafe.CallerMode,address,address).
   --> test/helpers/Builder.sol:142:47:
    |
142 |         (initialMode, initialSender, dummy) = vm.readCallers();
    |                                               ^^^^^^^^^^^^^^^^

Error: 
Compilation failed
```

There doesn't seem to be any explicit example about importing `CallerMode` in the documentation, just a [high level summary](https://book.getfoundry.sh/cheatcodes/read-callers#signature) without import paths.

I feel dumb to ask here but there but googling brings no example, anywhere. 

Any help is appreciated!

**Comment by mds1** [comment]
Typically this means you have two different `Vm.sol` instances being used. For example your `import {VmSafe} from "forge-std/Vm.sol"` may be using `lib/forge-std` while your `vm.readCallers()` is using a `vm` from `lib/some-other-dep/lib/forge-std`. Check your remappings, imports, and inheritance to track down the source of the issue

**Comment by brickpop** [comment]
Thank you for the comment @mds1 

`vm.readCallers()` is consumed within a `Test` contract. Nothing more is needed to trigger the issue:

<img width="818" alt="image" src="https://github.com/foundry-rs/forge-std/assets/4456749/35a370d7-6c42-4978-a85f-dfed1d4d6c5f">

Remappings look like:
```
@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/
@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/
@ensdomains/ens-contracts/=lib/ens-contracts/
forge-std/=lib/forge-std/src/
```

I assume that `VmSafe` from `VM.sol` is the intended place to import for using `readCallers()`

**Comment by brickpop** [comment]
> Try `Vm.sol` which is the correct casing of the file name, not `VM.sol`. If that doesn’t work please provide a repo to reproduce with.

That did the trick Matt, thank you!

It would be great if [the documentation](https://book.getfoundry.sh/cheatcodes/read-callers#signature) showed the intended import paths. That might save some future issues in here. 

Thank you for such a great development suite, guys
