### ISSUE TITLE
Add new random cheatcodes

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/forge-std#562]
ref https://github.com/foundry-rs/foundry/pull/7960

**Comment by mds1** [comment]
Was going to implement this but have a question first—left comments on https://github.com/foundry-rs/foundry/pull/7960

**Comment by mds1** [comment]
@mattsse bump on https://github.com/foundry-rs/foundry/pull/7960#discussion_r1619015391

**Comment by mds1** [comment]
Closed by https://github.com/foundry-rs/forge-std/pull/572
