### ISSUE TITLE
Problem installing forge-std library

### ISSUE THREAD

**Issue by macrojocodes** [foundry-rs/forge-std#576]
I have been having a problem with downloading "**forge-std library**" ,  when I use the forge init --force , there is no lib folder getting created at all , I somehow manually added the lib folder the forge-std library in it .
but i still cannot use import **"forge-std/Test.sol"**  directly like patrick is using , please help me

**Comment by mds1** [comment]
If I create an empty directory, `cd` into it, run `touch a.txt`, then run `forge init --force` it works as expected

Can you provide the exact steps to reproduce your problem (e.g. are you in an empty dir, exact forge command, etc)? What foundry version are you using? You can check with `forge --version`
