### ISSUE TITLE
BUG StdStorage: Unexpected 'find' function behavior when dynamic array length matches searched element value

### ISSUE THREAD

**Issue by perorinchain** [foundry-rs/forge-std#580]
For example, when setting the following dynamic array with length 3:
```
uint256[] public dynamicArray = [3, 3, 3];
```
The `find` function with key(0) should result in `uint256(keccak256(abi.encode(uint256(<slot number>))))`, but now returns `<slot number>`:
```
stdstore
    .target(someAddress)
    .sig("dynamicArray(uint256)")
    .with_key(uint256(0))
    .find();
```

**Comment by mds1** [comment]
@klkvr can you take a look at this one?

**Comment by perorinchain** [comment]
@klkvr 
This occurred in a local test environment, not in real-world contracts. 
Thanks for fixing it quickly.
