### ISSUE TITLE
feat: add `tearDown()` method that is called at the end for each unit test for Test contract

### ISSUE THREAD

**Issue by ZenGround0** [foundry-rs/forge-std#617]
### Component

Forge

### Describe the feature you would like

While writing forge unit tests it would be useful to have a function like `setUp` that is called at the end of each unit test.  I propose calling this `tearDown`.

Looking through the test runner code it looks like there is something similar for invariant tests (`afterInvariant`) but nothing currently for unit tests.

### Additional context

For my particular use case I am testing that a record keeping contract is being correctly updated during contract execution.  To do this I add expected state deltas at each point the state should be changed and then call a final assertion on the record keeper at the end of each test.  It would be convenient and less error prone if I could add this final assertion to a single tearDown() call that the framework would add onto each test for me.

**Comment by yash-atreya** [comment]
Hey @ZenGround0 

I think what you're looking for can be accomplished like so: 

```solidity
abstract contract AfterTest {
    modifier checkAfterTest() {
        _;
        afterTest();
    }

    function afterTest() public virtual;
}

contract AfterTestModifier is AfterTest, Test {
    uint256 test;

    function testSomething() public checkAfterTest {
        console.log("testSomething");
        test = 100;
    }

    function afterTest() public override {
        require(test != 0);

        assertEq(test, 101);
    }
}

```

Closing this for now. Feel free to reopen if this doesn't solve your issue.
