### ISSUE TITLE
"restartPrank" Helper

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/forge-std#63]
### Component

Forge

### Describe the feature you would like

I think the need to start a global prank in the `setUp` function but deactivate it in certain tests is a pretty common scenario.

To deactivate the global prank, I have to run two commands:

```solidity
vm.stopPrank();
vm.startPrank(otherUser);
```

Lest forge fails with the following error:

> [FAIL. Reason: You have an active prank already.]

It would be nice if there was a cheatcode that could atomically perform these two commands: a `restartPrank` cheatcode that accepts an address as an argument to be passed to `startPrank`.

**Comment by paulrberg** [comment]
@brockelmore your example captures exactly what I had in mind.

But I do want to note that I would expect `changePrank` to function like `startPrank` - that is, it should persist for all subsequent calls.

**Comment by dsam82** [comment]
@brockelmore @ZeroEkkusu anyone working on this, can I take a stab at it?

Seems straightforward.
