### ISSUE TITLE
Support for storage find in Vyper-compiled contracts

### ISSUE THREAD

**Issue by hexonaut** [foundry-rs/forge-std#73]
Seems like you guys are using the same trick we are to scan storage for arbitrary variables. One issue I ran into when adding this to spells-mainnet for Maker is that Vyper uses an inverted format for mappings as you can [see here](https://github.com/makerdao/spells-mainnet/blob/master/src/DssSpell.t.base.sol#L657). Might be worthwhile to support Vyper contracts with find as it only doubles the search space.

**Comment by brockelmore** [comment]
we should support this currently because we actually record the the sloads in the evm and grab them from the evm via a cheatcode. So we iterate through *read* slots, so if it gets read, it doesn’t matter how the slot was computed.
