### ISSUE TITLE
Installation failed.

### ISSUE THREAD

**Issue by ssghost** [foundry-rs/forge-std#75]
System: MacOS X 10.15
Foundry forge version: forge 0.2.0 (a63e56d 2022-04-10T00:12:58.599340+00:00)
Use the command line that Readme.md mentioned: `forge install foundry-rs/forge-std`
Error result:
<img width="515" alt="Screenshot 2022-05-20 at 13 57 59" src="https://user-images.githubusercontent.com/6882971/169461154-4a27ac06-f989-46de-b745-0f4acb4a2e68.png">

**Comment by ZeroEkkusu** [comment]
@ssghost, I cannot remember how to replicate this, but I know this is not an issue with Forge Std.

Could you try the following somewhere, it should work:

```bash
forge init temp
cd temp
forge install Rari-Capital/solmate
```

**Comment by ssghost** [comment]
Thanks @ZeroEkkusu , it worked.
