### ISSUE TITLE
`forge snapshot` hangs with `--fork-url` arg

### ISSUE THREAD

**Issue by Sabnock01** [foundry-rs/forge-std#94]
Forge version: `forge 0.2.0 (9b2d95d 2022-06-23T00:13:03.193579407Z)`

When running `forge snapshot` with the `--fork-url` argument to account for tests using mainnet forking, the output hangs without finishing or the command terminating. 

This is the output from the most recent run with `RUST_LOG=ethers=trace` set which overflows the terminal ending with the 19 tests from `WitchV2.t.sol` and never proceeding.
[forge-issue.txt](https://github.com/foundry-rs/forge-std/files/8968990/forge-issue.txt)

**Comment by ZeroEkkusu** [comment]
Transferring to Foundry!

**Comment by ZeroEkkusu** [comment]
I don't have the org permission, wanna open there instead @Sabnock01?
