### ISSUE TITLE
Feature request: cheatcode to expect ERC-20 token balance change

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/forge-std#96]
In Waffle, there is a chai matcher for testing whether a contract call changes the ERC-20 token balance of an account:

[changeTokenBalance](https://ethereum-waffle.readthedocs.io/en/latest/matchers.html#change-token-balance)

Which can be used like this:

```javascript
await expect(() => token.transfer(walletTo.address, 200))
  .to.changeTokenBalance(token, walletTo, 200);

await expect(() => token.transferFrom(wallet.address, walletTo.address, 200))
  .to.changeTokenBalance(token, walletTo, 200);
```

It would be nice to have an equivalent VM cheatcode for this.

**Comment by ZeroEkkusu** [comment]
Closing, as this is linked to https://github.com/foundry-rs/forge-std/issues/97.

If this is a mistake, we'll reopen.
