### ISSUE TITLE
Feature request: cheatcode to expect ETH balance change

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/forge-std#97]
In Waffle, there is a chai matcher for testing whether a contract call changes the ETH balance of an account:

[changeEtherBalance](https://ethereum-waffle.readthedocs.io/en/latest/matchers.html#change-ether-balance)

Which can be used like this:

```javascript
await expect(() => wallet.sendTransaction({to: walletTo.address, value: 200}))
  .to.changeEtherBalance(walletTo, 200);

await expect(await wallet.sendTransaction({to: walletTo.address, value: 200}))
  .to.changeEtherBalance(walletTo, 200);
```

It would be nice to have an equivalent VM cheatcode for this.

**Comment by gakonst** [comment]
dont think we want to bloat the interface, rather keep it simple and do it with requires. i understand that chai provides a lot of nice utils but dont think we should go for a 1:1 match to them

**Comment by paulrberg** [comment]
That's fair.

Though I think @gakonst that you have closed this "as completed" (new GitHub feature). I think it should have been closed as "not planned".

<img width="408" alt="Screen Shot 2022-07-15 at 11 31 00 AM" src="https://user-images.githubusercontent.com/8782666/179185348-da4b98f9-9816-448f-a190-c7f4cc772166.png">

**Comment by gakonst** [comment]
Fixed! The default ctrl+enter flow was to close as completed hehe
